version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    groups:
      typescript:
        patterns: ["typescript", "@typescript-eslint/*"]
      eslint:
        patterns: ["eslint", "eslint-*"]
      prisma:
        patterns: ["prisma", "@prisma/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /infra/docker
    schedule: { interval: weekly }
